(def e3 (js/document.getElementById "app"))
(def element (js/document.getElementById "app"))
(def e1 (js/document.getElementById "player"))
(.dispatchEvent e1 (new js/KeyboardEvent "keydown" {:key "Space"}))
(set! (.. e1 -style -color) "red")
(set! (.. e1 -style -color) "blue")
(.-tagName e1)
